[package]
name = "fsd"
description = "A library for interacting with FSD (https://github.com/kuroneko/fsd)"
authors = ["Erica Taylor <rickytaylor26@gmail.com>"]
license = "BSD"
version = "0.1.0"
edition = "2021"

[lib]
name = "fsd"

[dependencies]
